package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/m-this/tf2-archipelago/gamedata"
)

func quoted(value string) string { return strconv.QuoteToASCII(value) }

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: pluginbuffs <output.inc>")
		os.Exit(2)
	}
	var out strings.Builder
	out.WriteString("// Code generated by gamedata/cmd/pluginbuffs; DO NOT EDIT.\n\n")
	writeStrings := func(name string, value func(gamedata.WeaponBuff) string) {
		fmt.Fprintf(&out, "char %s[][] = {\n", name)
		for _, buff := range gamedata.WeaponBuffs {
			fmt.Fprintf(&out, "    %s,\n", quoted(value(buff)))
		}
		out.WriteString("};\n\n")
	}
	writeStrings("g_WeaponBuffKeys", func(buff gamedata.WeaponBuff) string { return buff.Key })
	writeStrings("g_WeaponBuffWeapons", func(buff gamedata.WeaponBuff) string { return buff.Weapon })
	writeStrings("g_WeaponBuffAttributes", func(buff gamedata.WeaponBuff) string { return buff.Attribute })
	writeStrings("g_WeaponBuffDescriptions", func(buff gamedata.WeaponBuff) string { return buff.Description })
	out.WriteString("float g_WeaponBuffValues[] = {\n")
	for _, buff := range gamedata.WeaponBuffs {
		fmt.Fprintf(&out, "    %.2f,\n", buff.Value)
	}
	out.WriteString("};\n\nbool g_WeaponBuffAdditive[] = {\n")
	for _, buff := range gamedata.WeaponBuffs {
		fmt.Fprintf(&out, "    %t,\n", buff.Additive)
	}
	out.WriteString("};\n\n// Item definition index, then zero-based buff index.\n")
	out.WriteString("int g_WeaponBuffByDefinition[][2] = {\n")
	for index, buff := range gamedata.WeaponBuffs {
		for _, definition := range buff.DefIndexes {
			fmt.Fprintf(&out, "    { %d, %d },\n", definition, index)
		}
	}
	out.WriteString("};\n")
	if err := os.WriteFile(os.Args[1], []byte(out.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
