"""Emit gamedata/weapons.go from the bot mod's weapon pools and the game's own schema.

The pools are what the mod will hand a bot; the schema is what the weapon is
called. Neither is written by hand here, so the catalogue cannot drift from
either.
"""
import re, sys

MOD = "/home/mathis/projects/tf2-mvm-bots/source/redbots3/loadouts.sp"
SCHEMA = "/home/mathis/tf2-native/tf-dedicated/tf/scripts/items/items_game.txt"
ENGLISH = "/home/mathis/tf2-native/tf-dedicated/tf/resource/tf_english.txt"

SLOTS = {"PRIMARY": "primary", "SECONDARY": "secondary", "MELEE": "melee",
         "PDA2": "pda2", "BUILDING": "building"}
CLASSES = {"SCOUT": "scout", "SOLDIER": "soldier", "PYRO": "pyro",
           "DEMOMAN": "demoman", "HEAVY": "heavyweapons", "ENGINEER": "engineer",
           "MEDIC": "medic", "SNIPER": "sniper", "SPY": "spy"}

def pools():
    for line in open(MOD, encoding="utf-8", errors="replace"):
        m = re.match(r'public const int WEAPONS_([A-Z]+)_([A-Z0-9]+)\[\] = \{(.*)\};', line.strip())
        if not m:
            continue
        cls, slot, body = m.group(1), m.group(2), m.group(3)
        if cls not in CLASSES or slot not in SLOTS:
            print(f"skipping WEAPONS_{cls}_{slot}", file=sys.stderr)
            continue
        idx = [int(t) for t in (x.strip() for x in body.split(","))
               if t != "TF_ITEMDEF_DEFAULT" and int(t) < 15000]
        yield CLASSES[cls], SLOTS[slot], idx

def items():
    """Every numbered item block, by index.

    Brace counting rather than a regex: item blocks nest (tags, attributes,
    visuals), and a non-greedy match ends at the first inner close, which
    silently truncated two thirds of them.
    """
    text = open(SCHEMA, encoding="utf-8", errors="replace").read()
    start = re.search(r'\n\t"items"\n\t\{', text)
    i, end = start.end(), len(text)
    out = {}
    while i < end:
        m = re.compile(r'\n\t\t"(\d+)"\s*\n\t\t\{').search(text, i)
        if not m:
            break
        depth, j = 1, m.end()
        while j < end and depth:
            if text[j] == '{':
                depth += 1
            elif text[j] == '}':
                depth -= 1
            j += 1
        out.setdefault(int(m.group(1)), text[m.end():j - 1])
        i = j
    return out

def english():
    out = {}
    raw = open(ENGLISH, encoding="utf-16", errors="replace").read()
    for m in re.finditer(r'"([^"]+)"\s+"([^"]*)"', raw):
        out.setdefault(m.group(1).lower(), m.group(2))
    return out

# A repaint of a gun already in the list. The 15xxx block is not the whole of
# them: the Botkillers and the Festives sit in the 6xx to 11xx range with the
# real weapons, and a Scout primary menu of twelve Scatterguns is the thing
# this catalogue exists to avoid.
RESKIN = re.compile(r"\bBotkiller\b|^Festive |^Australium ", re.I)


def reskin(name):
    return bool(RESKIN.search(name))


def quote(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    schema, loc = items(), english()
    rows, missing = [], []
    for cls, slot, idx in pools():
        for n in idx:
            inner = schema.get(n, "")
            internal = re.search(r'"name"\s+"([^"]+)"', inner)
            internal = internal.group(1) if internal else ""
            # "Upgradeable TF_WEAPON_X" is the MvM stock weapon, which the
            # menu already offers as stock. Two entries for one gun is noise.
            if internal.startswith("Upgradeable "):
                continue
            token = re.search(r'"item_name"\s+"([^"]+)"', inner)
            name = loc.get(token.group(1).lstrip("#").lower(), "") if token else ""
            if not name and internal and "TF_" not in internal:
                name = internal
            if not name:
                missing.append((cls, slot, n, internal))
                continue
            if reskin(name):
                continue
            rows.append((cls, slot, n, name))

    for row in missing:
        print(f"no name for {row}", file=sys.stderr)
    rows.sort(key=lambda r: (r[0], r[1], r[3].lower()))
    print(f"{len(rows)} entries, {len(missing)} dropped for want of a name", file=sys.stderr)

    out = ['''// Code generated by gamedata/cmd/weapons. DO NOT EDIT.

package gamedata

// Weapon is one item the bot mod will hand a defender bot: the definition
// index the mod writes into its loadout file, and what to call it in a menu.
type Weapon struct {
\tDefIndex int
\tName     string
\tClass    string
\tSlot     string
}

// Weapons is every non-stock item the mod can give a bot, drawn from the
// WEAPONS_* pools in source/redbots3/loadouts.sp. Stock is not in here: the
// mod spells it as the default index and every menu offers it separately.
//
// The reskins are left out. The 15xxx and 30xxx blocks are Festive and
// Botkiller repaints of guns already listed, and a Scout primary menu of
// thirty entries where twenty are Scatterguns is not a menu.
var Weapons = []Weapon{''']
    for cls, slot, n, name in rows:
        out.append('\t{%d, %s, %s, %s},' % (n, quote(name), quote(cls), quote(slot)))
    out.append("}")
    return "\n".join(out) + "\n"

if __name__ == "__main__":
    sys.stdout.write(main())
