// Command popcounts counts the giants and tanks of every wave of every
// population file in a directory, and prints the Go table gamedata commits.
//
// Valve's files sit inside tf2_misc_dir.vpk, so the directory has to be
// extracted first; the #base files a mission names have to be beside it.
//
// Usage: go run ./cmd/popcounts <dir> > wave_kills_generated.go
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/m-this/tf2-archipelago/gamedata"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: popcounts <dir>")
		os.Exit(2)
	}
	dir := os.Args[1]
	resolve := func(name string) []byte {
		body, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil
		}
		return body
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var names []string
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), "mvm_") && strings.HasSuffix(entry.Name(), ".pop") {
			names = append(names, entry.Name())
		}
	}
	sort.Strings(names)
	fmt.Println("// Code generated by gamedata/cmd/popcounts. DO NOT EDIT.")
	fmt.Println("//")
	fmt.Println("// Giants and tanks per wave, read out of the population files in")
	fmt.Println("// tf2_misc_dir.vpk. Regenerate after a Valve update to those files.")
	fmt.Println()
	fmt.Println("package gamedata")
	fmt.Println()
	fmt.Println("var waveKillsByPopFile = map[string][]WaveKills{")
	for _, name := range names {
		body := resolve(name)
		waves, err := gamedata.CountWaveKills(body, resolve)
		if err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", name, err)
			os.Exit(1)
		}
		fmt.Printf("\t%q: {\n", strings.TrimSuffix(name, ".pop"))
		for _, wave := range waves {
			if len(wave.Uncertain) > 0 {
				fmt.Fprintf(os.Stderr, "%s: a wave's giants depend on a random draw in %v\n", name, wave.Uncertain)
			}
			fmt.Printf("\t\t{Giants: %d, Tanks: %d},\n", wave.Giants, wave.Tanks)
		}
		fmt.Println("\t},")
	}
	fmt.Println("}")
}
