// Command pluginassets writes the SourcePawn table for loose community files
// that must be registered in Source's client download table.
package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/m-this/tf2-archipelago/gamedata"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: pluginassets <output.inc>")
		os.Exit(2)
	}
	if err := os.WriteFile(os.Args[1], []byte(generate()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() string {
	assets := gamedata.CommunityClientAssets()
	var out strings.Builder
	out.WriteString("// Code generated by gamedata/cmd/pluginassets; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "#define CommunityClientAssetCount %d\n\n", len(assets))
	out.WriteString("char g_CommunityClientAssetMaps[][] = {\n")
	for _, asset := range assets {
		fmt.Fprintf(&out, "    %s,\n", strconv.QuoteToASCII(asset.Map))
	}
	out.WriteString("};\n\nchar g_CommunityClientAssetPaths[][] = {\n")
	for _, asset := range assets {
		fmt.Fprintf(&out, "    %s,\n", strconv.QuoteToASCII(asset.Path))
	}
	out.WriteString("};\n")
	return out.String()
}
